#!/bin/bash

HAS_ISSUES=0

for file in $(git diff --name-only --staged); do
    if [[ $file == *.rs ]]; then
        if rustfmt --check --skip-children $file 2>/dev/null; then
            echo "$file"
            HAS_ISSUES=1
        fi
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo "Your code has formatting issues in files listed above. Format your code with \`cargo fmt\` or call rustfmt manually."
exit 1
