on:
  pull_request:
  push:
    branches:
      - main

name: Build, Test and Lint

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.13.2'
      - run: mix deps.get
      - run: mix test
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path native/rustsolver/Cargo.toml
  fmt:
    name: format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path native/rustsolver/Cargo.toml
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.13.2'
      - run: mix deps.get
      - run: mix format --check-formatted
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path native/rustsolver/Cargo.toml
          name: cargo clippy output
