on:
  push:
      branches:
        - main

name: Fly Deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: 🚀 to prod
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.3
          with:
            args: "deploy"