on:
  push:
      branches:
        - main

name: Fly Deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: 🚀 to prod
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set GITHUB_SHA
          id: vars
          run: echo "::set-output name=GIT_SHORT_SHA::$(git rev-parse --short $GITHUB_SHA)"
        - uses: superfly/flyctl-actions@1.3
          env:
            GIT_SHORT_SHA: ${{ steps.vars.outputs.GIT_SHORT_SHA }}
          with:
            args: "deploy --build-arg GIT_SHORT_SHA=${GIT_SHORT_SHA}"
